### ISSUE TITLE
In CurrentMotorState- configure frequent "ON" messages from MotorControl Program

### ISSUE THREAD

**Issue by LikithBC** [ashroom1/BC-Water-Control#3]
In CurrentMotorState Topic- configure such that frequent "ON" messages are sent from MotorControl Board.
Currently it'll send "ON" message only once.
Use existing Timer if possible.

**Comment by ashroom1** [comment]
Implemented and to be tested.

**Comment by LikithBC** [comment]
Compile error on line 420 of Motor Control
(Code: https://github.com/ashroom1/BC-Water-Control/commit/12e43ea074e2df8c83fb61efb64eb5ea1a7d6fca)

Bug fixed & implemented on Real time system with below code, (Code has not been pushed to github)

if (CurrentMotorState_message_flag) {   //Reapeated on/off message
        if (motor_state)
            check_and_publish(TOPIC_CurrentMotorState, ON, 0);
        else if (!motor_state)
            check_and_publish(TOPIC_CurrentMotorState, OFF, 0); 
      CurrentMotorState_message_flag = 0;
    }
