### ISSUE TITLE
Wi-Fi Transmit (Tx) power to be increased for Motor Control

### ISSUE THREAD

**Issue by LikithBC** [ashroom1/BC-Water-Control#4]
This could possibly fix Disconnection issue

**Comment by LikithBC** [comment]
We concluded that the tx power is set to max by default.

**Comment by LikithBC** [comment]
WiFi.setOutputPower(20.5);
to set Max Tx Power

**Comment by ashroom1** [comment]
WiFi.setOutputPower(20.5) to both tank and motor.
